CREATE OR REPLACE TABLE project.raw.store (
  s_store_sk INT,
  s_store_id STRING,
  s_rec_start_date DATE,
  s_rec_end_date DATE,
  s_closed_date_sk INT,
  s_store_name STRING,
  s_number_employees INT,
  s_floor_space INT,
  s_hours STRING,
  s_manager STRING,
  s_market_id INT,
  s_geography_class STRING,
  s_market_desc STRING,
  s_market_manager STRING,
  s_division_id INT,
  s_division_name STRING,
  s_company_id INT,
  s_company_name STRING,
  s_street_number STRING,
  s_street_name STRING,
  s_street_type STRING,
  s_suite_number STRING,
  s_city STRING,
  s_county STRING,
  s_state STRING,
  s_zip STRING,
  s_country STRING,
  s_gmt_offset DECIMAL(5,2),
  s_tax_percentage DECIMAL(5,2))
USING delta
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.domainMetadata' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd')