CREATE TABLE IF NOT EXISTS project.std.std_webSales(
    ws_sold_date_sk Int,
    ws_ship_date_sk Int,
    ws_item_sk Int,
    ws_bill_customer_sk Int,
    ws_bill_cdemo_sk Int,
    ws_bill_hdemo_sk Int,
    ws_bill_addr_sk Int,
    ws_ship_customer_sk Int,
    ws_ship_cdemo_sk Int,
    ws_ship_hdemo_sk Int,
    ws_ship_addr_sk Int,
    ws_web_page_sk Int,
    ws_web_site_sk Int,
    ws_ship_mode_sk Int,
    ws_warehouse_sk Int,
    ws_promo_sk Int,
    ws_order_number Int,
    ws_quantity Int,
    ws_wholesale_cost Decimal(7,2),
    ws_list_price Decimal(7,2),
    ws_sales_price Decimal(7,2),
    ws_ext_discount_amt Decimal(7,2),
    ws_ext_sales_price Decimal(7,2),
    ws_ext_wholesale_cost Decimal(7,2),
    ws_ext_list_price Decimal(7,2),
    ws_ext_tax Decimal(7,2),
    ws_coupon_amt Decimal(7,2),
    ws_ext_ship_cost Decimal(7,2),
    ws_net_paid Decimal(7,2),
    ws_net_paid_inc_tax Decimal(7,2),
    ws_net_paid_inc_ship Decimal(7,2),
    ws_net_paid_inc_ship_tax Decimal(7,2),
    ws_net_profit Decimal(7,2)
)
USING delta
TBLProperties(
  'delta.checkpoint.writeStatsAsJson'='false',
  'delta.checkpoint.writeStatsAsStruct'='true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.domainMetadata' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd'
)